#Minecraft server properties
#Thu Jun 18 16:24:40 KST 2026
accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=hard
enable-code-of-conduct=false
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=JVoD2UfspDZQQ2TyPNMfHhKyfqSI39zQmoQELxE7
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=10
max-tick-time=60000
max-world-size=29999984
motd=QSMP - Purpur 26.1.2
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=https\://cdn.modrinth.com/data/ZltblCOt/versions/uTOUpxTI/true-ending-dragon-music-v1.zip
resource-pack-id=9c85ebf6-4430-516e-9cfd-12283748b65d
resource-pack-prompt={"text"\:"True Ending official dragon music pack is optional but recommended for the full boss fight."}
resource-pack-sha1=93aaaacdde99601ad519e1970255e52be8a09b0e
server-ip=
server-name=Unknown Server
server-port=25565
simulation-distance=8
spawn-monsters=true
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false
